name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Profile Cards
    steps:
      # 1️⃣ Faz checkout do repositório com permissão de push
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2️⃣ Configura usuário do Git
      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 3️⃣ Gera os cards
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: adrian971029
          AUTO_PUSH: false   # evita que a action tente fazer push sozinha

      # 4️⃣ Lista arquivos gerados (debug)
      - name: List generated files
        run: ls -R ./profile-summary-card-output/

      # 5️⃣ Commit e push apenas se houver alterações
      - name: Commit and push cards
        run: |
          if [ -n "$(git status --porcelain ./profile-summary-card-output/)" ]; then
            git add ./profile-summary-card-output/
            git commit -m "Update GitHub profile cards"
            git push
          else
            echo "No changes to commit"
          fi
